name: Update NiceGost

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-22.04
    name: Run
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Run NiceGost Update
        run: |
          sudo chmod +x NiceGost.sh
          ./NiceGost.sh TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
  
      - name: Check for nicegost
        run: |
          if [ -e nicegost ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add NiceGost-amd64.deb NiceGost-arm64.deb README.md
            git commit -m "Update NiceGost on $(TZ='Asia/Singapore' date "+%Y/%m/%d %H:%M:%S")"
            git push origin main --force
          else
            echo "NiceGost doesn't need an update."
          fi
