name: Update

on:
#  schedule:
#    - cron: '0 20 * * 0'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-20.04
    name: Run
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0

      - name: Run Script
        run: sudo chmod +x 1.sh && sudo bash 1.sh
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
