name: Update

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-20.04
    name: Run
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0

      - name: Run Script
        run: |
          MESSAGE="这是一条来自GitHub Actions的测试消息。"
          URL="https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"
          curl -s -X POST "$URL" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
